### ISSUE TITLE
`basicauth.Identifier` gives `AttributeError` when no credentials provided

### ISSUE THREAD

**Issue by johansen** [talons/talons#29]
Attempting to use `basicauth.Identifier` within a `Middleware` gives me an `AttributeError` because no auth credentials have been provided. However, the expected behavior would be that the `identify` method returns `False`, leading to an HTTP 401 status and prompting the provision of credentials.

To reproduce:

``` sh
mkdir ./tmp
virtualenv ./tmp
cd ./tmp
./bin/pip install talons gunicorn
touch .htpasswd
```

Create a file `test.py` with these contents:

``` python
import falcon
from talons.auth import middleware, basicauth, htpasswd

class Dummy:
    def on_get(self, req, resp):
        resp.body = "dummy"

config = {
          'htpasswd_path': '.htpasswd'
}

auth_middleware = middleware.create_middleware(identify_with=basicauth.Identifier,
                                               authenticate_with=htpasswd.Authenticator,
                                               **config)

app = falcon.API(before=[auth_middleware])
app.add_route("/", Dummy())
```

Then:

``` sh
./bin/gunicorn test:app
```

and load `http://localhost:8000` in your favorite web browser. In the browser you'll get an "Internal Server Error" message. In the terminal you'll see something like:

``` sh
Error handling request
Traceback (most recent call last):
  File "/Users/joshuahansen/tmp/lib/python3.3/site-packages/gunicorn/workers/sync.py", line 93, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/joshuahansen/tmp/lib/python3.3/site-packages/gunicorn/workers/sync.py", line 134, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/joshuahansen/tmp/lib/python3.3/site-packages/falcon/api.py", line 96, in __call__
    responder(req, resp, **params)  # pragma: no cover
  File "/Users/joshuahansen/tmp/lib/python3.3/site-packages/falcon/api_helpers.py", line 261, in do_before
    action(req, resp, kwargs)
  File "/Users/joshuahansen/tmp/lib/python3.3/site-packages/talons/auth/middleware.py", line 97, in __call__
    if i.identify(request):
  File "/Users/joshuahansen/tmp/lib/python3.3/site-packages/talons/auth/basicauth.py", line 50, in identify
    auth_type, user_and_key = http_auth.split(six.b(' '), 1)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by johansen** [comment]
Unfortunately, it's not that easy. The "basic authentication" protocol requires that the 401 response include a `WWW-Authenticate: Basic` header. However, raising of the 401 response is currently the responsibility not of `basicauth.Identifier` but of `Middleware`, and `Middleware` doesn't know that it needs to send `WWW-Authenticate`, and for some auth schemes that might even be a bug.

It seems that `basicauth.Identifier` needs to be raising its own 401 responses so it can include the proper header. Or implementers of `interfaces.Identifies` need a way to add custom headers to a 401 response.

**Comment by jaypipes** [comment]
Hi! Thanks for logging the issue. I'm a bit swamped at $work this week but will be able to look into this over the weekend.

All the best,
-jay

**Comment by johansen** [comment]
No problem, I understand.

**Comment by johansen** [comment]
Any progress?

**Comment by jaypipes** [comment]
Hi! Sorry for the delay. Now fixed in master. Will push out a new release shortly (when fixing this I noticed some issues with unit tests and a failing linter run... so I'm going to fix those up and then release)

**Comment by johansen** [comment]
Great news, thanks for getting on this
