### ISSUE TITLE
authenticator requires only one parameter

### ISSUE THREAD

**Issue by dukedougal** [talons/talons#36]
I am getting this error:

talons.exc.BadConfiguration: external_authn_callable has an invalid function signature. The function must take only a single parameter.

This is my authenticator:

class MMAuthenticator(interfaces.Authenticates):

```
def __init__(self, **config):
    print('Init authenticate.....')

def authenticate(self, identity):
    print('Authenticating.....')
    return True
```

Does this error seem right? Or should it be allowing for the first argument to be self if the method is in a class?

**Comment by jaypipes** [comment]
What is the configuration values you are supplying?

**Comment by dukedougal** [comment]
I've stopped looking at this and have taken another path.  Thanks anyway! :-)
