### ISSUE TITLE
Is talons the recommended way to integrate authentication into Falcon?

### ISSUE THREAD

**Issue by catmeme** [talons/talons#39]
It seems talons hasn't had much love recently. Is this the recommended way to integrate authentication into falcon framework?

**Comment by jaypipes** [comment]
Hi! Sorry for the delayed response!

Yes, you're right that Talons has not seen much love recently. Talons works with the 0.3 and before series of Falcon, not with the current Falcon tree. I have some ongoing work to bring it up to speed with modern 0.4+ Falcon distributions and should have that done in a couple weeks and released to PyPI.

Best,
-jay
